server:
  port: 8181
  servlet:
    context-path: /api
spring:
  application:
    name: recipe-service
#  datasource:
#    url: jdbc:h2:mem:recipe-db
#    username: root
#    password: password
#    driverClassName: org.h2.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/recipe_db
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
#  datasource:
#    url: jdbc:postgresql://localhost:5432/recipe-db
#    username: root
#    password: root
#    driverClassName: org.postgresql.Driver
#    sql:
#      init:
#        platform: postgres
#    jpa:
#      generate-ddl: true
#      database: POSTGRESQL
#      show-sql: true
#      hibernate:
#        ddl-auto: create-drop


#    database-platform: org.hibernate.dialect.H2Dialect
